In [56]:
import pandas as pd
import numpy as np

import requests 
from pprint import pprint

Cont_2019_db = pd.read_csv('./DataSources/rate2018_tmdb.csv')

#Cont_2019_db = pd.read_csv('./DataSources/2017best_movie.csv')

#Cont_2019_db1 = pd.read_csv('./DataSources/theContendersDF_OMBD.csv')
#Cont_2019_db1.head()

In [57]:
Cont_2019_db

                                           Name  Popularity
0                                         Venom     368.719
1   Fantastic Beasts: The Crimes of Grindelwald     315.827
2   The Seven Deadly Sins: Prisoners of the Sky     252.200
3                                  The Predator     179.214
4                             Bohemian Rhapsody     162.230
5           The House with a Clock in Its Walls     155.089
6                                    The Grinch     152.814
7                                    Robin Hood     133.976
8                 Mission: Impossible - Fallout     129.802
9                     Ralph Breaks the Internet     117.495
10                                      The Nun     114.786
11                       Avengers: Infinity War     101.706
12                     The Christmas Chronicles     100.215
13                                   Peppermint      95.167
14                              The Equalizer 2      80.009
15                               A Star Is Born      73.935
16                                Incredibles 2      72.403
17                 The Girl in the Spider's Web      66.727
18                                 Night School      66.054
19                                      The Meg      62.196

In [58]:
Cont_2019_db_name = Cont_2019_db['name']

KeyError: 'name'

In [55]:
# use api.tmdb.org due to problem of 'query limit is 40'
base_url ='https://api.tmdb.org/3/search/movie?'
api_key = 'api_key=d5b4e5d5145be601d4640d76efd791e3'
query = '&query='
query_base_url = base_url + api_key + query

# best_pic_info: get the movie summary information 
best_pic_2019 = []

for i in range(len(Cont_2019_db_name)): 
    release_year = '2018'
    movie_info = query_base_url + Cont_2019_db_name[i] + '&year=' + release_year
    print(movie_info)
    response=requests.get(movie_info).json()
    best_pic_2019.append(response['results'])

https://api.tmdb.org/3/search/movie?api_key=d5b4e5d5145be601d4640d76efd791e3&query=Call Me by Your Name&year=2018
https://api.tmdb.org/3/search/movie?api_key=d5b4e5d5145be601d4640d76efd791e3&query=Darkest Hour&year=2018
https://api.tmdb.org/3/search/movie?api_key=d5b4e5d5145be601d4640d76efd791e3&query=Dunkirk&year=2018
https://api.tmdb.org/3/search/movie?api_key=d5b4e5d5145be601d4640d76efd791e3&query=Get Out&year=2018
https://api.tmdb.org/3/search/movie?api_key=d5b4e5d5145be601d4640d76efd791e3&query=Lady Bird&year=2018
https://api.tmdb.org/3/search/movie?api_key=d5b4e5d5145be601d4640d76efd791e3&query=Phantom Thread&year=2018
https://api.tmdb.org/3/search/movie?api_key=d5b4e5d5145be601d4640d76efd791e3&query=The Post&year=2018
https://api.tmdb.org/3/search/movie?api_key=d5b4e5d5145be601d4640d76efd791e3&query=The Shape of Water&year=2018
https://api.tmdb.org/3/search/movie?api_key=d5b4e5d5145be601d4640d76efd791e3&query=Three Billboards Outside Ebbing, Missouri&year=2018
https://api.tmdb.org/3/search/movie?api_key=d5b4e5d5145be601d4640d76efd791e3&query=Moonlight&year=2018

In [46]:
len(best_pic_2019)

10

In [47]:
base_url1 = 'https://api.tmdb.org/3/movie/'

#language = '&language=en-US'
keyword = '/keywords?'
Winner2019_Details= []
keyword_details = []
tmdb_id_list = []
#keywords: https://api.themoviedb.org/3/movie/23383/keywords?api_key=d5b4e5d5145be601d4640d76efd791e3

for i in range(len(best_pic_2019)):
    print(i)
    tmdb_id = str(best_pic_2019[i][0]['id'])
    tmdb_id_list.append(best_pic_2019[i][0]['id'])
    detail_query_link = base_url1 + tmdb_id + '?' + api_key #+ language
    keywords_query_link = base_url1 + tmdb_id + keyword + api_key
    response = requests.get(detail_query_link).json()
    keywords_response = requests.get(keywords_query_link).json()
    Winner2019_Details.append(response)
    keyword_details.append(keywords_response)

0
1
2
3
4
5
6
7
8
9

IndexError: list index out of range

In [10]:
winning_keywords = []
keywords_list = []

for i in range(len(keyword_details)):
    for j in range(len(keyword_details[i]['keywords'])):
        winning_keywords.append(keyword_details[i]['keywords'][j]['name'])
    keywords_list.append(keyword_details[i]['keywords'])

In [11]:
revenue_list = []
budget_list = []
runtime_list = []
vote_average_list = []
vote_count_list =[]
pop_list = []
genre_list =[]
release_date_list = []


for i in range(len(Winner2019_Details)):
    revenue_list.append(Winner2019_Details[i]['revenue'])
    budget_list.append(Winner2019_Details[i]['budget'])
    runtime_list.append(Winner2019_Details[i]['runtime'])
    vote_average_list.append(Winner2019_Details[i]['vote_average'])
    vote_count_list.append(Winner2019_Details[i]['vote_count'])
    pop_list.append(Winner2019_Details[i]['popularity'])
    genre_list.append(Winner2019_Details[i]['genres'])
    release_date_list.append(Winner2019_Details[i]['release_date'])


release_month_list = []
for i in range(len(release_date_list)):
    release_month = release_date_list[i].split('-')
    release_month_list.append(release_month[1])
    

Cont_2019_db['id'] = pd.Series(tmdb_id_list).values
Cont_2019_db['revenue'] = pd.Series(revenue_list).values
Cont_2019_db['budget'] =  pd.Series(budget_list).values
Cont_2019_db['runtime'] = pd.Series(runtime_list).values
Cont_2019_db['vote_average'] = pd.Series(vote_average_list).values
Cont_2019_db['vote_count'] = pd.Series(vote_count_list).values
Cont_2019_db['popularity'] = pd.Series(pop_list).values
Cont_2019_db['genres'] = pd.Series(genre_list).values
Cont_2019_db['release_month'] = pd.Series(release_month_list).values
Cont_2019_db['keywords'] = pd.Series(keywords_list).values

In [12]:
def get_names(keywords):
    return '|'.join([x['name'] for x in keywords]) 



Cont_2019_db['keywords'] = Cont_2019_db['keywords'].apply(get_names)
Cont_2019_db['genres'] = Cont_2019_db['genres'].apply(get_names)

Cont_2019_db.head()

,Year,Award,won,name,id,revenue,budget,runtime,vote_average,vote_count,popularity,genres,release_month,keywords
0,2017,BEST PICTURE,False,Call Me by Your Name,398818,41063475,4000000,132,8.3,3722,16.849,Romance|Drama,09,italy|upper class|based on novel or book|swimm...
1,2017,BEST PICTURE,False,Darkest Hour,399404,147568410,30000000,125,7.3,2162,13.953,Drama|History,11,world war ii|biography|london underground|base...
2,2017,BEST PICTURE,False,Dunkirk,374720,525573161,100000000,107,7.4,7686,21.633,Action|Drama|History|Thriller|War,07,france|beach|europe|world war ii|evacuation|ge...
3,2017,BEST PICTURE,False,Get Out,497223,0,0,105,6.5,5,3.564,Action|Drama|Thriller,04,car bomb|blackmailer
4,2017,BEST PICTURE,False,Lady Bird,391713,76858273,10000000,94,7.3,2958,17.112,Comedy|Drama,09,coming of age|best friend|loss of job|catholic...

In [13]:
genre_weight_dict ={'Drama': 0.36587982832618027,\
                    'Romance': 0.12339055793991416,\
                    'Comedy': 0.0815450643776824,\
                    'History': 0.06759656652360516,\
                    'Thriller': 0.0611587982832618,\
                    'Crime': 0.05042918454935622,\
                    'Adventure': 0.046137339055793994,\
                    'War': 0.043991416309012876,\
                    'Action': 0.03755364806866953,\
                    'Mystery': 0.02467811158798283,\
                    'Fantasy': 0.022532188841201718,\
                    'Music': 0.022532188841201718,\
                    'Family': 0.0203862660944206,\
                    'Western': 0.015021459227467811,\
                    'Science Fiction': 0.01072961373390558,\
                    'Animation': 0.003218884120171674,\
                    'Horror': 0.003218884120171674,\
                    'other': 0.05882352941176469}

In [14]:
genre_list = list(Cont_2019_db['genres'])
w_genre_list = genre_weight_dict.keys()

weight=0
weight_list = []

for i in range(len(genre_list)):
    onefilm = genre_list[i].split('|')
    for j in range(len(onefilm)):
        if onefilm[j] in w_genre_list:
            weight  += genre_weight_dict[onefilm[j]]
        else:
             weight  += genre_weight_dict['other']
        
    weight_list.append(weight)
    weight = 0

In [15]:
Cont_2019_db['genre_weight'] = weight_list

In [16]:
Cont_2019_db.release_month = Cont_2019_db.release_month.astype(int)

In [17]:
Cont_2019_db['profit'] = Cont_2019_db['revenue'] - Cont_2019_db['budget']

In [22]:
Cont_2019_db

,Year,Award,won,name,id,revenue,budget,runtime,vote_average,vote_count,popularity,genres,release_month,keywords,genre_weight,profit
0,2017,BEST PICTURE,False,Call Me by Your Name,398818,41063475,4000000,132,8.3,3722,16.849,Romance|Drama,9,italy|upper class|based on novel or book|swimm...,0.489270,37063475
1,2017,BEST PICTURE,False,Darkest Hour,399404,147568410,30000000,125,7.3,2162,13.953,Drama|History,11,world war ii|biography|london underground|base...,0.433476,117568410
2,2017,BEST PICTURE,False,Dunkirk,374720,525573161,100000000,107,7.4,7686,21.633,Action|Drama|History|Thriller|War,7,france|beach|europe|world war ii|evacuation|ge...,0.576180,425573161
3,2017,BEST PICTURE,False,Get Out,497223,0,0,105,6.5,5,3.564,Action|Drama|Thriller,4,car bomb|blackmailer,0.464592,0
4,2017,BEST PICTURE,False,Lady Bird,391713,76858273,10000000,94,7.3,2958,17.112,Comedy|Drama,9,coming of age|best friend|loss of job|catholic...,0.447425,66858273
5,2017,BEST PICTURE,False,Phantom Thread,400617,46261438,35000000,131,7.2,1215,10.017,Drama|Romance,12,london england|wife husband relationship|obses...,0.489270,11261438
6,2017,BEST PICTURE,False,The Post,446354,174503458,50000000,116,7.0,1973,11.181,Drama|History,12,journalism|newspaper|biography|politics|govern...,0.433476,124503458
7,2017,BEST PICTURE,True,The Shape of Water,399055,194989655,19500000,123,7.3,5686,21.903,Drama|Fantasy|Romance,12,cold war|baltimore|fairy tale|government|super...,0.511803,175489655
8,2017,BEST PICTURE,False,"Three Billboards Outside Ebbing, Missouri",359940,158526998,15000000,115,8.2,4219,15.942,Crime|Drama,11,suicide|rape|small town|missouri|alcoholism|mu...,0.416309,143526998

In [19]:
features = ['id','budget','popularity','release_month','revenue','runtime','vote_average','vote_count','genre_weight','profit']

In [20]:
test_set_2019 = Cont_2019_db[features]

In [ ]:
#test_set_2019.to_csv('./DataSources/test2019_tmdb.csv')

In [21]:
test_set_2019.to_csv('./DataSources/test2017_tmdb.csv')